FROM python:3.12-slim
WORKDIR /srv
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# build_info.json is generated by CI (or scripts/deploy.sh) BEFORE the upload —
# .git is excluded from the build context, so it cannot be generated in here.
COPY . .
ENV PYTHONPATH=/srv PORT=8080
CMD exec uvicorn app.main:app --host 0.0.0.0 --port ${PORT}
